### PR TITLE
User Article Lists

### LINKED ISSUE #39: Save specific articles to custom user defined list

### PR DESCRIPTION
**Pull request by ronaldcohen1611**
Added new feature Custom User Articles, which allows users to create lists that can dynamically hold specific user articles.

### CODE REVIEW

**Review by rodrigomv29 — APPROVED** [review]
Looks good to me

**Review by Ballslamic — APPROVED** [review]
Looks great, runs well.

**Review by billyr06 — APPROVED** [review]
Everything is working as expected. As always, nice job!

**Comment by rodrigomv29** [comment]
EF0ED470-DB52-4062-A323-D0CBAF32B4D4
This is about as far as I got in the joke api

**Comment by rodrigomv29** [comment]
I have to restructure the App.tsx file to position it better

**Comment by rodrigomv29** [comment]
Deleting branch right now

**Pull request merged**
