### PR TITLE
Sorted search

### PR DESCRIPTION
**Pull request by billyr06**

### CODE REVIEW

**Review by rodrigomv29 — APPROVED** [review]
👍

**Review by chrism1001 — APPROVED** [review]

**Comment by chrism1001** [comment]
image
only issue is the article image and description are not rendering right, but besides that its good. nice work.

**Comment by billyr06** [comment]
Thanks for the review. I addressed issues mentioned and made the necessary changes.
-  added a function to remove html tags if they appeared in the article's desciption.
- added a stock image when the image from the article did not render (seems to be a problem when the article comes from google news).
- added links to the article image and article title.
- added some unit testing.

**Comment by Ballslamic** [comment]
Went through multiple search results using different options. Everything works very well!

**Review by Ballslamic — APPROVED** [review]

**Review by Ballslamic — APPROVED** [review]

**Pull request merged**
